using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ClientGarmentManagment.Helpers
{
    public static class Globals
    {
        public static Dictionary<string, string> GenderDictionary = new Dictionary<string, string>
        {
            {"M","Mens"},
            {"W","Womens"},
            {"Y","Youth"},
            {"T","Toddler"},
            {"I", "Infant" }
        };

        public static Dictionary<string, string> ColorHexDictionary = new Dictionary<string, string>
        {
            #region ColorHex
            {"Aloe","#89ad63"},
            {"Aqua","#7ec5d7"},
            {"Aquatic Blue","#475c87"},
            {"Army","#4d473b"},
            {"Ash","#cbc5c5"},
            {"Asphalt","#505457"},
            {"Athletic Heather","#9fa3ac"},
            {"Athletic Orange","#ff7824"},
            {"Atlantis","#a5cf00"},
            {"Aubergine","#4a2546"},
            {"Avocado","#e8e397"},
            {"Azalea","#fa63ff"},
            {"Baby Blue","#96aeca"},
            {"Banana","#e9dfa1"},
            {"Berry","#c13c7e"},
            {"Bimini Blue","#5e9cd0"},
            {"Black","#000000"},
            {"Blackberry","#4c2a54"},
            {"Blossom","#f4bed5"},
            {"Blue Dusk","#304050"},
            {"Blue Jean","#56667d"},
            {"Blue Woodland","#5965a5"},
            {"Brick","#83383d"},
            {"Bright Orange","#f6471e"},
            {"Bright Red","#770023"},
            {"Bright Royal","#252c60"},
            {"Brown","#4c382b"},
            {"Brown Savana","#584933"},
            {"Burgundy","#4d1a26"},
            {"Burnt Orange","#a85426"},
            {"Butter","#fddd8a"},
            {"Cactus Green","#858472"},
            {"Camel","#b57e45"},
            {"Camouflage Green","#3f412b"},
            {"Camouflage Sand","#a6a188"},
            {"Candy","#db78ff"},
            {"Cantaloupe","#fb7b4c"},
            {"Canvas Red","#9b1a2a"},
            {"Cardinal","#8b0000"},
            {"Cardinal Red","#cf005b"},
            {"Caribbean Blue","#008FB7"},
            {"Carolina Blue","#9cdbff"},
            {"Carrot","#e29162"},
            {"Cedar","#963846"},
            {"Celadon","#a6b385"},
            {"Chambray","#b9d9e6"},
            {"Charcoal","#3b3b3b"},
            {"Charcoal Heather","#575757"},
            {"Charity Pink","#d896a6"},
            {"CharityPink","#d896a6"},
            {"Cherry Red","#e00033"},
            {"Chestnut","#72524a"},
            {"Chili","#8d3649"},
            {"Chocolate","#422f2b"},
            {"Ciel Blue","#627aa7"},
            {"Citrus Yellow","#f5f294"},
            {"City Green","#394b37"},
            {"Cobalt","#0272a4"},
            {"Cobblestone","#b8b19f"},
            {"Columbia","#4782cb"},
            {"Copper","#b7593e"},
            {"Coral","#de4a48"},
            {"Coral Silk","#ea5462"},
            {"Corporate Blue","#454f69"},
            {"Cream","#f1eada"},
            {"Crimson","#983844"},
            {"Crunchberry","#d96c89"},
            {"Currant","#6d3359"},
            {"Daffodil Yellow","#ffdc8e"},
            {"Daisy","#ffd433"},
            {"Dark Ash","#adadac"},
            {"Dark Chocolate","#423500"},
            {"Dark Grey Heather","#544f55"},
            {"Dark Heather","#62666f"},
            {"Deep Forest","#243932"},
            {"Deep Heather","#5d616a"},
            {"Deep Navy","#2c2f41"},
            {"Deep Red","#b00035"},
            {"Deep Royal","#294086"},
            {"Deep Teal","#105366"},
            {"Denim","#454c5c"},
            {"Denim Blue","#435f84"},
            {"Desert Camouflage","#786b3f"},
            {"Eco Green","#018452"},
            {"Eco Natural","#e3ddcd"},
            {"Eco Red","#b31a2e"},
            {"Eco White","#f5f5f5"},
            {"Eggplant","#582b48"},
            {"Emerald Green","#25614e"},
            {"Evergreen","#0f634b"},
            {"Express Yellow","#ddb762"},
            {"Fatigue Green","#56534a"},
            {"Flamingo","#e896ad"},
            {"Flo Blue","#617abd"},
            {"Forest","#2c4532"},
            {"Forest Green","#0e4d1c"},
            {"Frost Pink","#CDB7BA"},
            {"Frost Sky","#C7D8E8"},
            {"Fuchsia","#dd2760"},
            {"Galapagos Blue","#00595a"},
            {"Garnet","#7b212d"},
            {"Gold","#ffa61a"},
            {"Gold Nugget","#cb9f54"},
            {"Granite","#868b8e"},
            {"Grass","#509465"},
            {"Gravel","#8c8c8c"},
            {"Green Apple","#4a9157"},
            {"Green Digital","#677050"},
            {"Green Woodland","#3e4c2d"},
            {"Grey","#8c9099"},
            {"Heather","#9e999f"},
            {"Heather Black","#282924"},
            {"Heather Blue","#43507d"},
            {"Heather Brown","#694f40"},
            {"Heather Cardinal","#9c3e4c"},
            {"Heather Charcoal","#43507d"},
            {"Heather Dark Grey","#727175"},
            {"Heather Green","#369668"},
            {"Heather Grey","#7c777d"},
            {"Heather Indigo","#5b6b82"},
            {"Heather Navy","#2b3b52"},
            {"Heather Purple","#7a679f"},
            {"Heathered Blue","#3a4968"},
            {"Heathered Green","#25573d"},
            {"Heliconia","#ff00ff"},
            {"Hemp","#505843"},
            {"Honey","#ffb83d"},
            {"Hot Pink","#E2447E"},
            {"Ice Gray","#9ea09f"},
            {"Ice Grey","#e4e4f2"},
            {"Independence Red","#9d2330"},
            {"Indigo","#455876"},
            {"Indigo Blue","#4696e3"},
            {"Iris","#52a8ff"},
            {"Irish Green","#008a4d"},
            {"Ivy","#4c6f69"},
            {"Jade","#1d9383"},
            {"Jade Dome","#01858a"},
            {"Jade Green","#008f78"},
            {"Kelly","#016d56"},
            {"Kelly Green","#007656"},
            {"Key Lime","#92c371"},
            {"Khaki","#998d77"},
            {"Kiwi","#5ba621"},
            {"Lagoon","#44b6d0"},
            {"Lagoon Blue","#4cb6c6"},
            {"Lake","#525e6e"},
            {"Lavender","#9a8ea4"},
            {"Leaf","#537d4f"},
            {"Lemon Zest","#F7D760"},
            {"Light Aqua","#7ec5d7"},
            {"Light Blue","#baedff"},
            {"Light Green","#608176"},
            {"Light Pink","#ffb8ff"},
            {"Light Steel","#8a8184"},
            {"Lilac","#c3a2bf"},
            {"Lime","#83cb67"},
            {"Lime Green","#9dc863"},
            {"Lime wedge","#dbdfaf"},
            {"Maize Yellow","#e4b744"},
            {"Mandarin Orange","#f27000"},
            {"Maroon","#612b39"},
            {"Mauve","#c7a7ab"},
            {"Melon","#f27652"},
            {"Metro Blue","#002b7a"},
            {"Midnight","#191970"},
            {"Military Green","#1f2e07"},
            {"Mint","#acd89b"},
            {"Mocha","#745447"},
            {"Moss","#606b58"},
            {"Moss Green","#889c79"},
            {"Mustard","#c8a257"},
            {"Natural","#dfd3c3"},
            {"Natural Organic","#e7dbcb"},
            {"Navy","#252a41"},
            {"Oatmeal","#D5CAB8"},
            {"Ocean Blue","#619dc1"},
            {"Oceana","#56adba"},
            {"Old Gold","#f09916"},
            {"Olive","#2d3e00"},
            {"Orange","#ff5e17"},
            {"Orange Sorbet","#df8b4f"},
            {"Orchid","#b8baff"},
            {"Oxford Gray","#6f6669"},
            {"Pacific Yellow","#f2d942"},
            {"Pale Blue","#b0e0e6"},
            {"Pale Green","#98fb98"},
            {"Pale Pink","#ffb6c1"},
            {"Pale Yellow","#f5e39c"},
            {"Paprika","#d54042"},
            {"Pebble","#a18d74"},
            {"Pebble Brown","#7d6b69"},
            {"Pepper","#4a4a4a"},
            {"Periwinkle","#7e94cd"},
            {"PFD White","#ffffff"},
            {"Pine Green","#284c3f"},
            {"Pink","#ffc0cb"},
            {"Pink Woodland","#fc8abe"},
            {"Pistachio","#c5e693"},
            {"Plum","#3b223b"},
            {"Prairie Dust","#738639"},
            {"Pure Gold","#fbc15c"},
            {"Purple","#800080"},
            {"Putty","#8e826b"},
            {"Raspberry","#752139"},
            {"Red","#ff0000"},
            {"River Blue","#8098b4"},
            {"Rose Blossom","#ff6bf7"},
            {"Royal","#006bfa"},
            {"Royal Blue","#006bfa"},
            {"Royal Caribe","#126c9e"},
            {"Russet","#954328"},
            {"Rusty Bronze","#954328"},
            {"Safari","#716e5e"},
            {"Safety Green","#cdff4f"},
            {"Safety Orange","#ff741a"},
            {"Salmon","#ffcccc"},
            {"Sand","#e6dfcf"},
            {"Sand Digital","#8b764f"},
            {"Sandstone","#a59f8f"},
            {"Sapphire","#009cba"},
            {"Scrub Green","#44a48d"},
            {"Seafoam Blue","#94c5bf"},
            {"Serene Green","#aebfa6"},
            {"Shamrock Green","#008e4f"},
            {"Silver","#b8bcbf"},
            {"Sky","#90f0e4"},
            {"Smoke","#5d5553"},
            {"Smoke Gray","#5d5553"},
            {"Soft Cream","#d3c4ad"},
            {"Soft Green","#acd093"},
            {"Soft Pink","#efcfd0"},
            {"Sport Grey","#a9a5a6"},
            {"Sports Grey","#818080"},
            {"Spring Green","#8ba26c"},
            {"Spring Yellow","#e7df7a"},
            {"Steel Blue","#4682b4"},
            {"Stone Blue","#79a6ad"},
            {"Stonewashed Blue","#7e93a4"},
            {"Stonewashed Green","#848a7e"},
            {"Storm Grey","#696d70"},
            {"Tan","#d2b48c"},
            {"Tangerine","#ff8a45"},
            {"Teal","#008080"},
            {"Teal Ice","#b2cec0"},
            {"Team Purple","#4b2e5c"},
            {"Tennessee Orange","#e64823"},
            {"Texas Orange","#e66000"},
            {"Tropical Pink","#ce477f"},
            {"True Blue","#3c70a0"},
            {"True royal","#4169e1"},
            {"Turf Green","#007a2a"},
            {"Turquoise","#40e0d0"},
            {"Tweed","#3f3f44"},
            {"Twilight Blue","#1a2f49"},
            {"Uniform Navy","#2b2c42"},
            {"Urban Digital","#424242"},
            {"Urban Woodland","#424242"},
            {"Vegas Gold","#e5bd79"},
            {"Very Pink","#cd6892"},
            {"Violet","#6e8cff"},
            {"Watermelon","#f25b6c"},
            {"White","#ffffff"},
            {"Willow","#465957"},
            {"Wine","#4b2535"},
            {"Winterberry","#451944"},
            {"Wow Pink","#d74681"},
            {"Yam","#975940"},
            {"Yellow","#fbe669"},
            {"Yellow Haze","#ffdb87"}
            #endregion
        };
    }
}
